import os
import shutil
import subprocess
from datetime import datetime
from pathlib import Path

import toml

# --- CONFIGURATION ---
RUST_PROJECT_DIR = "ScanCodeSyncDesktop"
WEBSITE_DIR = "HomeWebsite"
CARGO_TOML_PATH = os.path.join(RUST_PROJECT_DIR, "Cargo.toml")
RELEASES_HTML_PATH = os.path.join(WEBSITE_DIR, "releases.html")
WIX_BIN_PATH = os.path.abspath("wix314-binaries")


def increment_version(version_str):
    major, minor, patch = map(int, version_str.split("."))
    print(f"\n--- ScanCodeSync Release Manager ---")
    print(f"Current version: {version_str}")
    print(f" [1] Patch ({major}.{minor}.{patch + 1})")
    print(f" [2] Minor ({major}.{minor + 1}.0)")
    print(f" [3] Major ({major + 1}.0.0)")
    print(f" [Any other key] Skip increment")

    choice = input("Selection: ")
    if choice == "1":
        return f"{major}.{minor}.{patch + 1}"
    if choice == "2":
        return f"{major}.{minor + 1}.0"
    if choice == "3":
        return f"{major + 1}.0.0"
    return version_str


def update_releases_html(version, files):
    """Generates/Updates releases.html with a modern UI."""
    date_str = datetime.now().strftime("%B %d, %Y")
    links_html = "".join(
        [
            f'<li><a class="download-btn" href="{version}/{f}">Download {f}</a></li>'
            for f in files
        ]
    )

    content = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Releases | ScanCodeSync</title>
    <style>
        body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; background: #f8f9fa; color: #333; line-height: 1.6; padding: 40px 20px; }}
        .container {{ max-width: 600px; margin: 0 auto; }}
        h1 {{ border-bottom: 2px solid #dee2e6; padding-bottom: 10px; }}
        .card {{ background: white; padding: 25px; border-radius: 12px; box-shadow: 0 4px 6px rgba(0,0,0,0.05); border: 1px solid #e9ecef; }}
        .version-tag {{ background: #007bff; color: white; padding: 4px 12px; border-radius: 20px; font-size: 0.9em; font-weight: bold; }}
        ul {{ list-style: none; padding: 0; margin-top: 20px; }}
        .download-btn {{
            display: inline-block;
            background: #28a745; color: white;
            padding: 10px 20px; border-radius: 6px;
            text-decoration: none; font-weight: bold;
            transition: background 0.2s; margin-bottom: 10px;
        }}
        .download-btn:hover {{ background: #218838; }}
        .footer {{ margin-top: 40px; font-size: 0.85em; color: #6c757d; text-align: center; }}
    </style>
</head>
<body>
    <div class="container">
        <h1>ScanCodeSync Releases</h1>
        <div class="card">
            <span class="version-tag">Latest Release</span>
            <h2>Version {version}</h2>
            <p>Released on {date_str}</p>
            <ul>{links_html}</ul>
        </div>
        <div class="footer">
            &copy; 2026 ScanCodeSync | Generated by Release Builder
        </div>
    </div>
</body>
</html>
"""
    with open(RELEASES_HTML_PATH, "w") as f:
        f.write(content)
    print(f"✅ Generated {RELEASES_HTML_PATH}")


def main():
    # 1. Path Verification
    if not os.path.exists(WIX_BIN_PATH):
        print(f"❌ Error: {WIX_BIN_PATH} folder missing.")
        return

    # 2. Versioning
    data = toml.load(CARGO_TOML_PATH)
    current_version = data["package"]["version"]
    new_version = increment_version(current_version)

    if new_version != current_version:
        data["package"]["version"] = new_version
        with open(CARGO_TOML_PATH, "w") as f:
            toml.dump(data, f)
        print(f"✅ Updated Cargo.toml to v{new_version}")

    # 3. Build
    print(f"🚀 Compiling MSI for v{new_version}...")
    try:
        subprocess.run(
            ["cargo", "wix", "--bin-path", WIX_BIN_PATH],
            cwd=RUST_PROJECT_DIR,
            check=True,
        )
    except subprocess.CalledProcessError:
        print("❌ Build failed. Check the output above.")
        return

    # 4. Cleanup/Move and Web Update
    dest_path = Path(WEBSITE_DIR) / new_version
    dest_path.mkdir(parents=True, exist_ok=True)
    wix_path = Path(RUST_PROJECT_DIR) / "target" / "wix"

    moved_files = []
    for file in wix_path.glob("*.msi"):
        shutil.copy2(file, dest_path / file.name)
        moved_files.append(file.name)
        print(f"  -> Moved: {file.name}")

    if moved_files:
        update_releases_html(new_version, moved_files)
        print(f"\n🎉 Success! Files are in {dest_path}")
        # Automatically open the new page
        os.startfile(os.path.abspath(RELEASES_HTML_PATH))
    else:
        print("⚠️ No MSI files were found in target/wix/")


if __name__ == "__main__":
    main()
