[package]
name = "ScanCodeSyncDesktop"
version = "0.0.2"
edition = "2024"
license = "GPL-3.0"
authors = [ "Ollie Lynas <sync@ollielynas.com>",]
homepage = "https://sync-home.ollielynas.com"

[dependencies]
anyhow = "1.0.102"
atomic-progress = "0.1.2"
chrono = "0.4.44"
crossbeam-channel = "0.5.15"
directories = "6.0.0"
egui-macroquad = "0.17.3"
exiftool = "0.3.1"
fastrand = "2.3.0"
ffmpeg-sidecar = "2.4.0"
image = "0.25.10"
macroquad = "0.4.14"
open = "5.3.3"
palette = "0.7.6"
rayon = "1.11.0"
rfd = "0.17.2"
rqrr = "0.10.1"
serde_json = "1.0.149"
typetag = "0.2.21"

[dependencies.catppuccin-egui]
version = "5.7"
default-features = false
features = [ "egui31",]

[dependencies.serde]
version = "1.0"
features = [ "derive",]

[package.metadata.wix]
product-icon = "src/favicon.ico"

[package.metadata.dist]
installers = [ "msi", "powershell", "shell",]
targets = [ "x86_64-pc-windows-msvc", "x86_64-unknown-linux-gnu", "apple-darwin",]
